version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports: ["6333:6333"]
    volumes:
      - ./qdrant_storage:/qdrant/storage

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: visual-search-api
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    ports: ["8000:8000"]
    volumes:
      - ../images:/app/images:ro
      - ../outputs:/app/outputs:ro
    depends_on: [qdrant]
